### ISSUE TITLE
Version checking issue with "00 Install npm" exercise

### ISSUE THREAD

**Issue by mark-walle** [npm/how-to-npm#115]
Encountered a mistake with the first exercise where it believes an older version of npm is later than my current version:
```
> how-to-npm verify
verifying that npm is installed...
You have version 4.1.2 installed.  Great!
Now let's see what the latest version is... wait for it...
The latest npm is: 4.4.1
You have version 4.1.2, but the latest is 4.4.1
Run `npm install npm -g` to upgrade it
(You can also just skip this if you want)
```

**Comment by mark-walle** [comment]
This may be my problem... :
> npm install npm -g
path.js:1142
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:1142:25)
    at Function.Module._resolveLookupPaths (module.js:391:17)
    at Function.Module._resolveFilename (module.js:461:31)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:79:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

**Comment by mark-walle** [comment]
I just changed to 4.4.1 in order to complete the workshop, but maybe how-to-npm should allow pre-releases to pass, or give explicit directions to not use pre-release versions.

**Comment by watilde** [comment]
thanks for reporting this! I think it's just a logic bug in a code:
https://github.com/workshopper/how-to-npm/blob/master/problems/00-install-npm/index.js#L53

I'm gonna fix it.

**Comment by myintmyatkyu** [comment]
Hi I got this error when I run how-to-npm verify at "00 install npm" exercise
I have passed all other exercises except this one. Thanks

> how-to-npm verify
verifying that npm is installed...
You have version 6.0.1 installed.  Great!
Now let's see what the latest version is... wait for it...
The latest npm is: 
/home/ec2-user/.nvm/versions/node/v6.14.1/lib/node_modules/how-to-npm/node_modules/semver/semver.js:295
    throw new TypeError('Invalid Version: ' + version);
    ^

>TypeError: Invalid Version: 
    at new SemVer (/home/ec2-user/.nvm/versions/node/v6.14.1/lib/node_modules/how-to-npm/node_modules/semver/semver.js:295:11)
    at compare (/home/ec2-user/.nvm/versions/node/v6.14.1/lib/node_modules/how-to-npm/node_modules/semver/semver.js:571:10)
    at Function.gt (/home/ec2-user/.nvm/versions/node/v6.14.1/lib/node_modules/how-to-npm/node_modules/semver/semver.js:600:10)
    at /home/ec2-user/.nvm/versions/node/v6.14.1/lib/node_modules/how-to-npm/problems/00-install-npm/index.js:53:18
    at ChildProcess.exithandler (child_process.js:190:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
