### ISSUE TITLE
when I type how-to-npm in terminal It gives me the following error

### ISSUE THREAD

**Issue by neon98** [npm/how-to-npm#133]
```
$ how-to-npm

module.js:340
    throw err;
          ^
Error: Cannot find module 'commandico'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/how-to-npm/node_modules/workshopper-adventure/index.js:2:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by watilde** [comment]
@neon98 Hello! Could you try to re-install how-to-npm again?

**Comment by neon98** [comment]
@watilde  It's done! thanks :)
