### ISSUE TITLE
Stucking at level 10.

### ISSUE THREAD

**Issue by jackzzjack** [npm/how-to-npm#26]
I was stuck in level 10, and I followed the following step.

<b>Step 1.  I change the module version</b>
# npm version 3.0.0

v3.0.0

<b>Step 2. Type "npm publish", it shows</b>
# npm publish

npm ERR! Linux 2.6.32-24-generic-pae
npm ERR! argv "node" "[MY_HOME_ROOT]/node-v0.12.4-linux-x86/bin/npm" "publish"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.2
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! Please include the following file with any support request:
npm ERR!    [MY_HOME_ROOT]/node_tutorials/tmp/npm-ch2/npm-debug.log

<b>Step 3. Finally, I type "how-to-npm verify" and it shows </b>
# how-to-npm verify

module.js:338
    throw err;
          ^
Error: Cannot find module '/home/G12/yutingkao23/.config/how-to-npm/registry/yuting/body.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.exports.verify (/mnt/autofs/home/G12/yutingkao23/node_tutorials/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/mnt/autofs/home/G12/yutingkao23/node_tutorials/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/mnt/autofs/home/G12/yutingkao23/node_tutorials/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/mnt/autofs/home/G12/yutingkao23/node_tutorials/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/mnt/autofs/home/G12/yutingkao23/node_tutorials/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:460:26)

**Is there any problem with above steps ?**

**Comment by kaiserhase** [comment]
I ran into the same issue. I believe it's because you aren't "logged in". I am currently using 'npm login' to see if it gets me past this error. I'll respond or edit if I get a result.

Edit: Didn't get it really to work, but I skipped ahead and gave up on worrying about the "completed" showing up. Only needed to run through for freecodecamp.com anyway.

**Comment by jackzzjack** [comment]
I'll try it later. Thanks for your advise.

**Comment by ashleygwilliams** [comment]
hi @jackzzjack ! hopefully @kaiserhase solved your issue. i am closing this now, please reopen if you are still having trouble.

**Comment by ghost** [comment]
I'm having this problem as well.  Used npm init 1.0.1 to update my version and then went to publish again.  It gave this: 

 npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/node" "/home/ubuntu/.nvm/versions/node/v4.4.0/bin/npm" "publish"
npm ERR! node v4.4.0
npm ERR! npm  v3.8.7
npm ERR! code ENEEDAUTH

npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/npm/npm-debug.log

Which is what it gave me through the first publish lesson.  However, where it passed me in the first publish exercise, this one says: 

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/@codergeist/npm/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.0/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26)

Not sure how to fix this.

**Comment by madfolio** [comment]
also having the same error. cannot use the login solution. when i try to do this the terminal hangs.

any ideas?

---

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/test/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/problems/11-dist-tag.js:42:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26)
