### ISSUE TITLE
Facing problem in task 10.

### ISSUE THREAD

**Issue by orvi2014** [npm/how-to-npm#39]
when I type `how-to-npm verify` in the terminal. It gives me the following error. 

```
  module.js:340
  throw err;
      ^
Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/nodeproject/body.json'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.exports.verify (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
at Shop.verify (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
at Shop.execute (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
at Shop.shop.execute (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/how-to-npm/index.js:37:45)
at Object.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/how-to-npm/index.js:86:8)
at Module._compile (module.js:456:26)
```

**Comment by ierhyna** [comment]
Same here. Have you found any solution?

**Comment by orvi2014** [comment]
No. I asked in chat but no one take care about that .

**Comment by Megabyteceer** [comment]
i got same problem. For fix, i create folder named 'registry' inside 'how-to-npm' folder.

**Comment by orvi2014** [comment]
@Megabyteceer Do you have any idea why this problem is create ? I mean behind the reason of this problem. I actually don't get the reason for this problem

**Comment by Megabyteceer** [comment]
Something in sources was changed, and it corrupted application behavour.
For me error happen after step 8. I think how-to-npm makes something like sandbox for publish and adduser comands, and its need registry folder.
Maybe your case has another reasons.

**Comment by nikszejna** [comment]
Same problem going through how-to-npm on c9.io. I had to make a new directory with the name of my project in the registry, then copy body.json from a project in the registry. From here I had to edit my version to one that how-to-npm found.

**Comment by lisbethmarianne** [comment]
Same problem. Someone should look at this. This is very frustrating if you run into this in a tutorial.
Edit: I found this is due to failing login. The task 02 should have thrown an error, but didn't.

**Comment by kwhms** [comment]
Hello, I am having this same problem. I did up through task 9 and then took a break. Returned today and started with task 10 Publish Again and am getting this error. I also ran `npm login` and then checked against `npm whoami`. My module definitely published and I can see it on npmjs. The error persists for tasks 10-12, but then on 13 `how-to-npm verify` was successful and marked `[COMPLETED]`
