### ISSUE TITLE
Install A Module: Unexpected token

### ISSUE THREAD

**Issue by jecxjo** [npm/how-to-npm#42]
Running on Freebsd, tried with both npm version 2.14.4 and 3.3.5, same results.

```
$ npm install @linclark/pkg
npm WARN package.json @jecxjo/how-to-npm@1.0.0 No repository field.
npm WARN package.json @jecxjo/how-to-npm@1.0.0 No README data
npm ERR! registry error parsing json
npm ERR! FreeBSD 10.1-RELEASE-p19
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@linclark/pkg"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4

npm ERR! Unexpected token ï¿½
ï¿½¿½ï¿½body.jsonIï¿½
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Debug log generated:

```
$ cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '@linclark/pkg' ]
2 info using npm@2.14.4
3 info using node@v4.1.1
4 verbose install initial load of /usr/home/jeff/sandbox/node/how-to-npm/package.json
5 warn package.json @jecxjo/how-to-npm@1.0.0 No repository field.
6 warn package.json @jecxjo/how-to-npm@1.0.0 No README data
7 verbose readDependencies loading dependencies from /usr/home/jeff/sandbox/node/how-to-npm/package.json
8 silly cache add args [ '@linclark/pkg', null ]
9 verbose cache add spec @linclark/pkg
10 silly cache add parsed spec Result {
10 silly cache add   raw: '@linclark/pkg',
10 silly cache add   scope: '@linclark',
10 silly cache add   name: '@linclark/pkg',
10 silly cache add   rawSpec: '',
10 silly cache add   spec: '*',
10 silly cache add   type: 'range' }
11 silly addNamed @linclark/pkg@*
12 verbose addNamed "*" is a valid semver range for @linclark/pkg
13 silly addNameRange { name: '@linclark/pkg', range: '*', hasData: false }
14 silly mapToRegistry name @linclark/pkg
15 silly mapToRegistry scope (from package name) @linclark
16 verbose mapToRegistry no registry URL found in name for scope @linclark
17 silly mapToRegistry using default registry
18 silly mapToRegistry registry http://localhost:15443/
19 silly mapToRegistry uri http://localhost:15443/@linclark%2fpkg
20 verbose addNameRange registry:http://localhost:15443/@linclark%2fpkg not in flight; fetching
21 verbose request uri http://localhost:15443/@linclark%2fpkg
22 verbose request no auth needed
23 info attempt registry request try #1 at 15:41:12
24 verbose request id 0d434097addd7d59
25 http request GET http://localhost:15443/@linclark%2fpkg
26 http 200 http://localhost:15443/@linclark%2fpkg
ï¿½¿½ï¿½body.jsonIï¿½¿½ï¿½
28 error registry error parsing json
29 verbose headers { 'content-length': '512',
29 verbose headers   connection: 'close',
29 verbose headers   date: 'Thu, 08 Oct 2015 15:41:12 GMT' }
30 silly get cb [ 200,
30 silly get   { 'content-length': '512',
30 silly get     connection: 'close',
30 silly get     date: 'Thu, 08 Oct 2015 15:41:12 GMT' } ]
31 verbose stack SyntaxError: Unexpected token ï¿½
ï¿½¿½ï¿½body.jsonIï¿½¿½
31 verbose stack     at Object.parse (native)
31 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:198:23)
31 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:171:14)
31 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
31 verbose stack     at emitTwo (events.js:87:13)
31 verbose stack     at Request.emit (events.js:172:7)
31 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1073:14)
31 verbose stack     at emitOne (events.js:82:20)
31 verbose stack     at Request.emit (events.js:169:7)
31 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1019:12)
32 verbose cwd /usr/home/jeff/sandbox/node/how-to-npm
33 error FreeBSD 10.1-RELEASE-p19
34 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@linclark/pkg"
35 error node v4.1.1
36 error npm  v2.14.4
37 error Unexpected token ï¿½
ï¿½¿½ï¿½body.jsonIï¿½
38 error If you need help, you may report this error at:
38 error     <https://github.com/npm/npm/issues>
39 verbose exit [ 1, true ]


npm ERR! Please include the following file with any support request:
npm ERR!     /usr/home/jeff/sandbox/node/how-to-npm/npm-debug.log
```

**Comment by ax3l** [comment]
Same here, I think the packages does not exist any more.
