### ISSUE TITLE
TypeError: process.stdin.setRawMode is not a function

### ISSUE THREAD

**Issue by kotAPI** [npm/how-to-npm#50]
I get this error while trying to install the module. 
I used npm install -g how-to-npm

```
TypeError: process.stdin.setRawMode is not a function
    at module.exports (C:\Users\Kothapalli\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\lib\menu.js:51:19)
    at Shop.showMenu (C:\Users\Kothapalli\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\index.js:258:16)
    at Shop.execute (C:\Users\Kothapalli\AppData\Roaming\npm\node_modules\how-to-npm\node_modules\adventure\index.js:122:14)
    at Shop.shop.execute (C:\Users\Kothapalli\AppData\Roaming\npm\node_modules\how-to-npm\index.js:37:45)
    at Object.<anonymous> (C:\Users\Kothapalli\AppData\Roaming\npm\node_modules\how-to-npm\index.js:86:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)

```

**Comment by shmily1140** [comment]
same to me

**Comment by kotAPI** [comment]
Closing
