### ISSUE TITLE
failed npm dist-tag

### ISSUE THREAD

**Issue by arduino731** [npm/how-to-npm#52]
$npm dist-tag add express@3.2.4 
it errors

what is your tips?

**Comment by lelo81** [comment]
I also need help!

C:\WebDev>npm dist-tag add howtonpm@1.0.2 mytag
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Users\llopes\Ap
pData\Roaming\npm\node_modules\npm\bin\npm-cli.js" "dist-tag" "add" "howto
npm@1.0.2" "mytag"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code E404

npm ERR! 404 missing : -/package/howtonpm/dist-tags

npm ERR! Please include the following file with any support request:
npm ERR!     C:\WebDev\npm-debug.log

**Comment by jacobwhitten** [comment]
Yeah, can't seem to get past this either. Using this as my command: npm dist-tag add @jacobwhitten\test-environment@1.3.0 testtag

**Comment by celogeek** [comment]
same error, here the full debug :

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/5.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'dist-tag',
1 verbose cli   'add',
1 verbose cli   'dev@1.0.0',
1 verbose cli   'test' ]
2 info using npm@3.8.3
3 info using node@v5.9.1
4 verbose dist-tag add test to dev@1.0.0
5 silly mapToRegistry name dev
6 silly mapToRegistry using default registry
7 silly mapToRegistry registry http://localhost:15443/
8 silly mapToRegistry data Result {
8 silly mapToRegistry   raw: 'dev',
8 silly mapToRegistry   scope: null,
8 silly mapToRegistry   name: 'dev',
8 silly mapToRegistry   rawSpec: '',
8 silly mapToRegistry   spec: 'latest',
8 silly mapToRegistry   type: 'tag' }
9 silly mapToRegistry uri http://localhost:15443/dev
10 verbose request uri http://localhost:15443/-/package/dev/dist-tags
11 verbose request no auth needed
12 info attempt registry request try #1 at 12:11:11
13 verbose request id 5a671af4eebab536
14 http request GET http://localhost:15443/-/package/dev/dist-tags
15 http 404 http://localhost:15443/-/package/dev/dist-tags
16 verbose headers { 'content-type': 'application/json',
16 verbose headers   date: 'Sun, 27 Mar 2016 10:11:11 GMT',
16 verbose headers   connection: 'keep-alive',
16 verbose headers   'content-length': '19' }
17 verbose stack Error: missing : -/package/dev/dist-tags
17 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
17 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:252:14)
17 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
17 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:199:22)
17 verbose stack     at emitTwo (events.js:100:13)
17 verbose stack     at Request.emit (events.js:185:7)
17 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1036:10)
17 verbose stack     at emitOne (events.js:95:20)
17 verbose stack     at Request.emit (events.js:182:7)
17 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:963:12)
18 verbose statusCode 404
19 verbose cwd /Users/celogeek/Documents/Devel/NodeJS/NodeSchool/HowToNPM/dev
20 error Darwin 15.4.0
21 error argv "/usr/local/Cellar/node/5.9.1/bin/node" "/usr/local/bin/npm" "dist-tag" "add" "dev@1.0.0" "test"
22 error node v5.9.1
23 error npm  v3.8.3
24 error code E404
25 error 404 missing : -/package/dev/dist-tags
26 verbose exit [ 1, true ]
```

**Comment by derekharmon** [comment]
For `npm dist-tag add` you must use a fully-qualified name (that includes your id and version) like this `npm dist-tag add @fudruckus/howtonode@1.0.1 beta` where `beta` is the new dist-tag.

For `npm dist-tag rm` the version is not required, since the dist-tag must be unique across all versions. So `npm dist-tag rm @fudruckus/howtonode beta` removes it.

Note also on Windows, the direction of the / matters.
