### ISSUE TITLE
Cannot verify 10 Publish Again: throws an error

### ISSUE THREAD

**Issue by outtech1** [npm/how-to-npm#61]
$ how-to-npm verify
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/tomasvolta/.config/how-to-npm/registry/@tomasvolta/npm/body.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.exports.verify (/usr/local/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/usr/local/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/usr/local/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/usr/local/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/usr/local/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:413:34)
Bons-MacBook-Pro:npm tomasvolta$ how-to-npm verify
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/tomasvolta/.config/how-to-npm/registry/@tomasvolta/npm/body.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.exports.verify (/usr/local/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/usr/local/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/usr/local/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/usr/local/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/usr/local/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:413:34)

**Comment by mmatthews1981** [comment]
I got something similar. 

$ how-to-npm verify
module.js:338
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/@meredithmatthews/tut/body.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.1.1/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:434:26)

**Comment by oky1** [comment]
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/oky1/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26)

**Comment by Sposito** [comment]
Mine is not working at all. any updates on that?

```

module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/@sposito/tut/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26)
```

**Comment by AJBoyle31** [comment]
I'm have the same exact error. Now it won't let me verify any of the next challenges. Has there been a fix?

**Comment by cupofjoey** [comment]
I tried to re-publish with the new version and got all of this. 

`````` module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/joehill/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.3/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26) ```

Removed my dir, and started again. Hopefully will resolve.


``````

**Comment by RBuddha** [comment]
cannot re-publish either:
module.js:327
    throw err;
    ^
...

**Comment by ghost** [comment]
Me too 
 $ how-to-npm verify skip
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/sample/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.4.5/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26)

**Comment by ghost** [comment]
i think updating the npm to latest version could be causing the issue, can any one try with old version?

**Comment by pahosler** [comment]
same /fcc/npm$ how-to-npm verify
module.js:341
    throw err;
    ^

**Comment by ltthanh** [comment]
I have same problem with npm v2.15.9 and npm v3.10.6. 

```
module.js:327
    throw err;
    ^

```

**Comment by CBedzz** [comment]
NPM 3.10.6  Same error today:

rror: Cannot find module '/Users/cbedo/.config/how-to-npm/registry/how-to-npm/body.json'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.exports.verify (/usr/local/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/usr/local/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/usr/local/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/usr/local/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/usr/local/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:556:32)

**Comment by kurumkan** [comment]
The error 
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/test/body.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/how-to-npm/problems/10-publish-again.js:33:14)
    at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.5.0/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:409:26)

I also can't run how-to-npm verify skip

**Comment by with0out** [comment]
same problem here.

```
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/vagrant/.config/how-to-npm/registry/@with0out/how-to-npm/body.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.exports.verify (/home/vagrant/.nvm/versions/node/v6.8.1/lib/node_modules/how-to-npm/problems/11-dist-tag.js:42:14)
    at Shop.verify (/home/vagrant/.nvm/versions/node/v6.8.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
    at Shop.execute (/home/vagrant/.nvm/versions/node/v6.8.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
    at Shop.shop.execute (/home/vagrant/.nvm/versions/node/v6.8.1/lib/node_modules/how-to-npm/index.js:37:45)
    at Object.<anonymous> (/home/vagrant/.nvm/versions/node/v6.8.1/lib/node_modules/how-to-npm/index.js:86:8)
    at Module._compile (module.js:570:32)
```

**Comment by imcodingideas** [comment]
I get the same problem with cloud9

> module.js:327
>     throw err;
>     ^
> 
> Error: Cannot find module '/home/ubuntu/.config/how-to-npm/registry/npmde/body.json'
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.exports.verify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/how-to-npm/problems/11-dist-tag.js:42:14)
>     at Shop.verify (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:157:15)
>     at Shop.execute (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/how-to-npm/node_modules/adventure/index.js:76:14)
>     at Shop.shop.execute (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/how-to-npm/index.js:37:45)
>     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v4.6.1/lib/node_modules/how-to-npm/index.js:86:8)
>     at Module._compile (module.js:409:26)

**Comment by zouhairkhallaf** [comment]
Same problem too :/

**Comment by pavazmo** [comment]
Same issue :'(
```

node publish     
module.js:327
    throw err;
    ^

Error: Cannot find module '/home/pat/prueba/promonitor/publish'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3

```

**Comment by bradicalone** [comment]
module.js:471
    throw err;

I take it the node.js course doesn't work anymore?

**Comment by rom-dos** [comment]
Same issue in npm 5.7.1
